title: Space
author: FabioKZ
description: > # this means to ignore newlines until "baseurl:"
  Description

# social links
twitter_username: FabioXKZ
github_username:  FabioKZ
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
